### ISSUE TITLE
Time marker headline text much too big

### ISSUE THREAD

**Issue by rezeau** [NDLANO/h5p-ndla-timeline#406]
Time marker headline text font-size much too big! (screenshot 1). Adding this rule to the styles.scss file fixes it (screenshot 2).
_h2.tl-headline.tl-headline-fadeout {
         font-size: 12px!important;
  }_
![2023-04-12_18-55-55](https://user-images.githubusercontent.com/503583/231530170-0c07f6af-23df-4d8d-97b6-5768eb75bbad.jpg)

**Comment by otacke** [comment]
@rezeau `!important` is a code smell. That rule should not be used unless there's no other way. Isn't there? And feel free to create a pull request instead of creating an issue.

**Comment by rezeau** [comment]
Please disregard this issue report. It was due to a conflict with the H2 styling in the Drupal theme I was using for my tests!
