### ISSUE TITLE
h5p pack h5p-ndla-timeline misses the dist files

### ISSUE THREAD

**Issue by rezeau** [NDLANO/h5p-ndla-timeline#407]
On my local dev drupal 7 set up I fail to pack h5p-ndla-timeline correctly. I do h5p pack h5p-ndla-timeline h5p-ndla-timeline.h5p -r (using the -r parameter to add the dependencies).
In the resulting h5p-ndla-timeline.h5p archive there is no sign of the dist folder. Which means installing this library to another environment results in this Error message
    _The file "dist/bundle.js" is missing from library: "H5P.NDLATimeline-0.0"
    The file "dist/bundle.css" is missing from library: "H5P.NDLATimeline-0.0"
    The uploaded file was not a valid h5p package_
**Note**.-
Given all the various issues with h5p-ndla-timeline that I have come across when trying to use it recently I wonder if this library has actually been tested on the various platforms where H5P libraries can be installed, e.g. WP, Moodle, Drupal... That's a pity because it has some useful elements which are missing from [the current h5p timeline library](https://github.com/h5p/h5p-timeline). Or am I missingn some important information?

**Comment by otacke** [comment]
@rezeau I just tried, but I don't see any problem. The distribution files get built just fine when running `npm run build`. Have you forgot to build the distribution files maybe?

Furthermore, there's no need to test an H5P content type on all kinds of platforms (unless you do a handful of special things), because content types are running on an abstraction layer.

**Comment by rezeau** [comment]
@otacke "The distribution files get built just fine when running _npm run build_." Yes, they do, but that's not the problem. The problem I have is that, once I've run _npm run build_ the h5p pack h5p-ndla-timeline h5p-ndla-timeline.h5p command does not insert the dist folder in the packed library. I hope I make myself clear. Have you tried to pack?
