### ISSUE TITLE
Wrong URL for running

### ISSUE THREAD

**Issue by rezeau** [NDLANO/h5p-ndla-timeline#424]
Instructions at https://github.com/NDLANO/h5p-ndla-timeline#running say:
Open the file dist/index.html in your browser
Which does not work. there is no index.html file in the dist folder.
The following works for me:
Open the file node_modules/@knight-lab/timelinejs/dist/embed/index.html in your browser

**Comment by otacke** [comment]
That seems to be outdated information. The H5P CLI tool should be used if one wants to run the content type without a platform (IMHO, instead of having custom solutions in a repository).

**Comment by janlindso** [comment]
Yeah, this seem more like a lacking README rather than an issue per se. We will try to make them better so they give a brief introduction and correct information.
