### ISSUE TITLE
Does not work in Moodle core h5p activity

### ISSUE THREAD

**Issue by rezeau** [NDLANO/h5p-ndla-timeline#489]
There are 2 ways to create/upload an H5P activity in Moodle: 
method a) using the 3rd-party plugin provided by the H5P team (the black icon), 
method b) using the core Moodle H5P activity (the blue icon).
In the current version of Moodle (4.2.x), h5p-ndla-timeline works OK using method a).
If using method b), it's possible to create/upload an h5p-ndla-timeline activity, but impossible to display it. Or rather there is a weird way of doing it. If you manage to click on the right of the line which is supposed to hold that content, it will open full screen and you will be able to view the content! But when you close/escape that full screen, it disappears again.

PS.- Interestingly I notice that there is exactly the same problem in LUMI... So not a bug special to Moodle core H5P.
![2023-09-10_19-09-15](https://github.com/NDLANO/h5p-ndla-timeline/assets/503583/af768eee-0bc2-44f6-8b77-ddf1139648c7)

**Comment by otacke** [comment]
I assume that it's a combination of the creators of NDLA Timeline not using the `embedType` of `iframe` for the content type (something that is bound to cause other trouble, too) but moodle enforcing displaying H5P content in iframe mode.

**Comment by rezeau** [comment]
@otacke That's a likely explanation. Is it the same for LUMI, then?

**Comment by otacke** [comment]
@rezeau What about Lumi? Does it show the same behavior?

**Comment by rezeau** [comment]
@otacke Yes, exactly the same behaviour (and same hack to manage to display it fullscreen).

**Comment by rezeau** [comment]
@otacke Thanks for your work, I will test your PR #492 ASAP and report here.
